/**
 * Beat the Brewer - Get Live Announcement Lambda Handler (READ-ONLY)
 *
 * GET /live-announcement?eventId=xxx
 *
 * Returns the most recent announcer commentary that was generated by the
 * scheduled generator (scheduledAnnouncer.js). This endpoint does NO Bedrock
 * or ElevenLabs calls and has no side effects, so the TV display and results
 * page can poll it freely without incurring cost.
 */

const { DynamoDBClient } = require('@aws-sdk/client-dynamodb');
const { DynamoDBDocumentClient, GetCommand } = require('@aws-sdk/lib-dynamodb');

const ANNOUNCEMENTS_TABLE_NAME = process.env.ANNOUNCEMENTS_TABLE_NAME;

const dynamoClient = new DynamoDBClient({});
const docClient = DynamoDBDocumentClient.from(dynamoClient);

const RESPONSE_HEADERS = { 'Content-Type': 'application/json' };

function buildResponse(statusCode, body) {
    return { statusCode, headers: RESPONSE_HEADERS, body: JSON.stringify(body) };
}

exports.handler = async (event) => {
    const method = event.httpMethod || event.requestContext?.http?.method;
    if (method === 'OPTIONS') return buildResponse(200, {});

    try {
        if (!ANNOUNCEMENTS_TABLE_NAME) {
            console.error('ANNOUNCEMENTS_TABLE_NAME is not set');
            return buildResponse(500, { hasUpdate: false, error: 'Server configuration error' });
        }

        const eventId = event.queryStringParameters?.eventId;
        if (!eventId) {
            return buildResponse(400, { hasUpdate: false, error: 'eventId query parameter is required' });
        }

        const result = await docClient.send(new GetCommand({
            TableName: ANNOUNCEMENTS_TABLE_NAME,
            Key: { eventId: eventId.trim() },
        }));

        const state = result.Item;
        if (!state || !state.lastAnnouncementText) {
            return buildResponse(200, { hasUpdate: false, message: 'No announcement yet' });
        }

        return buildResponse(200, {
            hasUpdate: true,
            text: state.lastAnnouncementText,
            audioUrl: state.lastAudioUrl || null,
            // Stable per-announcement id so the client can dedupe / avoid replaying.
            announcementId: state.lastAnnouncementAt,
            summary: {
                totalRatings: state.lastTotalRatings || 0,
                leader: state.lastLeader || null,
            },
        });
    } catch (error) {
        console.error('Unexpected error:', error);
        return buildResponse(500, { hasUpdate: false, error: 'Internal server error' });
    }
};
